version: '3.9'
services:
  ec-ms-rates:
    build:
      context: ../
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    links:
      - postgres
    environment:  
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=rates
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - FLYWAY_USER=postgres
    - FLYWAY_PASSWORD=postgres
    depends_on:
    - postgres
  postgres:
    image: postgres:13.4
    container_name: "postgres-ec-ms-rates"
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
    - '5432:5432'
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
  

