server:
  port: 8080
spring:
  jmx:
    enabled: false
  jpa:
    database: POSTGRESQL
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=rates
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:scripts/migration
    user: postgres
    password: postgres
    mixed: true
    validate-on-migrate: false
    baseline-on-migrate: true
logging:
  level:
    es:
      virtualcave: DEBUG
    org:
      springframework: INFO
    springfox:
      documentation: INFO
